### ISSUE TITLE
I can't view the full window

### ISSUE THREAD

**Issue by Drales1425** [Orso2p2n/four-souls-card-maker#2]
When I open the exe the window is cut off and I can't scroll or do anything about it.

![Captura de pantalla (68)](https://github.com/Orso2p2n/four-souls-card-maker/assets/159185338/66850112-931a-4fa9-8c6e-5bc9e2f063dd)
![Captura de pantalla (69)](https://github.com/Orso2p2n/four-souls-card-maker/assets/159185338/14d1936f-b24c-40ab-b7c4-840da436e965)

**Comment by Orso2p2n** [comment]
[Release 0.0.2](https://github.com/Orso2p2n/four-souls-card-maker/releases/tag/0.0.2) adds the ability to resize the window, fixing this issue.
