### ISSUE TITLE
monster and character card text alignment is off

### ISSUE THREAD

**Issue by TheBurgerTV2** [Orso2p2n/four-souls-card-maker#6]
character and monster card effect and lore text are further down than they should be, along with separators. this results in clashing with other card elements like starting item/monster rewards.
![Screenshot_1](https://github.com/Orso2p2n/four-souls-card-maker/assets/105133718/8ec9b2de-dd81-41d2-a37b-c80e74bd1be4)
![Screenshot_2](https://github.com/Orso2p2n/four-souls-card-maker/assets/105133718/34eda07e-b40e-4564-a157-b5983e0385cc)
![Screenshot_3](https://github.com/Orso2p2n/four-souls-card-maker/assets/105133718/05b2770b-fc45-4c6f-923a-2c75b75d7b1c)

**Comment by Orso2p2n** [comment]
Should be fixed with #8. Will be deployed with version 0.0.3.
